services:
  - type: worker
    name: wimbledon-bot-tenis
    runtime: python311
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python wimbledon_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
